# netlify.toml
[build]
  publish = "build"
  command = "npm run netlify-build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[build.environment]
  NODE_VERSION = "18"
  NETLIFY_USE_NEXTJS = "false"
  
# Remove the Next.js plugin completely
[plugins]