# netlify.toml
[build]
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[build.environment]
  NODE_VERSION = "18"
  
# Explicitly disable the Next.js plugin since this is a Vite project
[plugins]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    enable = false