[build]
  publish = "build"
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  
  [plugins.inputs]
  disable = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[build.environment]
  NODE_VERSION = "18"